import { VOTING_OPTIONS_MIN } from '../utils/constant-values'
import { Translations } from './translations'

export const EN_TRANSLATIONS: Translations = {
  app_title: 'DOTS',
  app_short_description: 'simple dot voting',
  how_does_it_work: 'HOW DOES IT WORK?',
  use_instruction_1: 'Someone creates a new poll.',
  use_instruction_2: 'That poll gets a unique code.',
  use_instruction_3: 'The code is given to all voters.',
  use_instruction_4: 'Voters get their own devices out.',
  use_instruction_5: 'Voters navigate to this web page.',
  use_instruction_6: 'Voters vote in the poll.',
  use_instruction_7: 'Results are examined.',
  dashboard_info_1: 'Seems you have used this app earlier.',
  dashboard_info_2: 'You can view your polls on dashboard:',
  view_dashboard: 'dashboard',
  mode_create_poll: 'create a poll',
  mode_vote_in_poll: 'vote in a poll',
  mode_view_poll: 'view a poll',
  language_FI: 'Finnish',
  language_EN: 'English',
  navigation_route_launch_page: 'home',
  navigation_route_create_poll: 'create',
  navigation_route_vote_in_poll: 'vote',
  navigation_route_view_poll: 'view',
  navigation_route_dashboard: 'dashboard',
  route_text_create_poll: 'create a poll',
  route_text_vote_in_poll: 'vote in a poll',
  route_text_view_poll: 'view a poll',
  route_text_dashboard: 'dashboard',
  too_short: 'too short',
  too_long: 'too long',
  required: 'required',
  too_many_options: 'Too many options...',
  too_little_options: 'Add at least one more...',
  options_must_be_unique: 'Voting options must be unique!',
  set_min_voting_options: `SET MIN ${VOTING_OPTIONS_MIN} VOTING OPTIONS`,
  add_voting_option_modal_title: 'Add voting option',
  placeholder_type_option_here: 'Type the voting option here...',
  set_voting_question: 'SET VOTING QUESTION',
  add_voting_question_modal_title: 'Set voting question',
  placeholder_type_question_here: 'Type the question here...',
  max_votes_per_person_title: 'Max total votes / person',
  mox_votes_per_option_title: 'Max votes / option / person',
  voting_is_anonymous: 'Voting is anonymous',
  show_status_when_voting: 'Poll status is shown when voting',
  general_add: 'Add',
  general_reset: 'Reset',
  general_submit: 'Submit',
  at_time_of_day: 'at',
  set_your_name: 'SET YOUR NAME',
  set_your_name_modal_title: 'Set your name or nickname',
  placeholder_type_name_here: 'Type your name here...',
  toast_default_error: 'ERROR',
  toast_default_warning: 'WARNING',
  toast_default_success: 'SUCCESS',
  toast_create_poll_error: 'Something went wrong. Could not create the poll. Please try again.',
  toast_create_poll_success: 'Your poll was successfully created!',
  option_count_cannot_exceed_total_count: 'too big',
  toast_open_poll_error: 'Something went wrong. COuld not open poll. Please try again.',
  open_poll_for_voting: 'Open poll',
  edit_poll: 'Edit poll',
  want_to_edit_poll_further: 'Would you like to change something?',
  can_still_edit_poll: 'You can still edit the poll if needed',
  if_poll_is_ready: 'If you are sure the poll is ready,',
  open_poll_for_voting_info: 'open the poll for voting',
  edit_poll_save_changes: 'Save changes',
  toast_edit_poll_error: 'Something went wrong. Could not save changes poll. Please try again.',
  toast_fetch_polls_by_id_or_code_error: 'Something went wrong. Could not find polls.'
}
